import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import CartSync from "@/components/cart/CartSync";
import FlyProvider from "@/components/providers/FlyProvider";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn("font-sans", geist.variable)}>
        <body className={`${poppins.variable} antialiased min-h-screen flex flex-col`}>
          <FlyProvider>
            <CartSync />
            <main className="flex-1">
              {children}
            </main>
          </FlyProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}